version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development  # Enable development mode (optional)
    volumes:
      - .:/app  # Mounts your local code to the container for live editing (development purpose)
